name: GuardAI Action CI

on:
  pull_request:
    branches:
      - main

jobs:
  test-guardai:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Run GuardAI Action
        id: guardai_test
        uses: ./
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          provider: "openai"
          directory: "."
          output_file: "guardai_output.txt"

      - name: Check GuardAI Output
        shell: bash
        run: |
          guardai_output_file="guardai_output.txt"

          # Check if the output file exists and is not empty
          if [[ ! -s "$guardai_output_file" ]]; then
            echo "No output detected from GuardAI action."
            exit 1
          fi

          echo "GuardAI action produced output successfully."
          cat "$guardai_output_file"
